### PR TITLE
Make list of clients in a room accessible

### PR DESCRIPTION
**Pull request by fodor0205**
I found it extremely useful to get the list of clients for a session / room.

This way I can access each socket with a `forEach` loop:

```
socketClients().forEach(function (s) {
    s.join('room');
});
```

### CODE REVIEW

**Comment by fodor0205** [comment]
I use send() to respond to the current socket with the callback.

Server side:

```
action(function join () {
    send({ foo: 'bar' });
});
```

On the client side:

```
socket.emit('join', {}, function (data) {
    console.log(data.foo); // bar
});
```

Sorry for combined pull request

**Comment by 1602** [comment]
Awesome. Could you please add some information about this feature to README.md file. Thanks!

**Comment by fodor0205** [comment]
I've added the informations to the readme, please check it. @1602

**Comment by 1602** [comment]
Thank you very much!

**Comment by fodor0205** [comment]
@1602 can you publish the changes to npm?

**Comment by 1602** [comment]
Published as co-socket@0.0.2

**Pull request merged**
